CREATE DEFINER=`remonty`@`%` PROCEDURE `test_WriteFile`()
LANGUAGE SQL
NOT DETERMINISTIC
CONTAINS SQL
SQL SECURITY DEFINER
COMMENT ''
BEGIN
SELECT id, title  INTO OUTFILE 'oedigi_k2_items.txt'
  FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
  LINES TERMINATED BY '\n'
  FROM oedigi_k2_items order by id desc limit 10;
END